### ISSUE TITLE
Dolby Atmos breaks Disney+

### ISSUE THREAD

**Issue by jamal2362** [reiryuki/Dolby-Atmos-OnePlus-8-Visible-Magisk-Module#1]
It is not possible to watch Disney+ content with this module.

Without module it runs wonderfully again.

**Comment by reiryuki** [comment]
@jamal2362 Sorry, open issue without logcat is not allowed
I will close this

**Comment by jamal2362** [comment]
Hello,
The Logcat say nothing.
I have edit your Module and i'm success fix it.

Regards
