### ISSUE TITLE
About dts or dts

### ISSUE THREAD

**Issue by devanshroy12** [reiryuki/Dolby-Atmos-OnePlus-8-Visible-Magisk-Module#2]
Hey it  will be be very glad if you could provide dts/dtsx for android 11.
As it is not running in android 11 i don't know why but it is so.
If you can do then please.
It is perfectly running on android 10 or below.
Thank you once again for your previous all work .
Thanks.
![image](https://user-images.githubusercontent.com/75802857/103410536-b2f9f980-4b91-11eb-96ac-5972cefc6bfa.png)

**Comment by reiryuki** [comment]
Sorry report without logcat is not allowed
